-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 21:53:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema maindb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maindb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maindb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

USE `maindb` ;

-- -----------------------------------------------------
-- Table `maindb`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindb`.`user_info` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  `biography` VARCHAR(45) NULL,
  `count_followers` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `7`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindb`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindb`.`followers` (
  `follower_one` INT NULL,
  `follower_two` INT NULL,
  `status` INT NULL,
  INDEX `id_idx` (`follower_one` ASC, `follower_two` ASC) VISIBLE,
  CONSTRAINT `3`
    FOREIGN KEY (`follower_one` , `follower_two`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindb`.`music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindb`.`music` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `autor_id` INT NULL,
  `image_path` VARCHAR(45) NULL,
  `likes_count` INT NULL,
  `musiccol` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `6`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindb`.`post` (
  `id` INT NOT NULL,
  `owner_id` INT NULL,
  `music_id` INT NULL,
  `count_likes` INT NULL,
  `post_text` VARCHAR(45) NULL,
  `image_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`music_id` ASC) VISIBLE,
  INDEX `id_idx1` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `4`
    FOREIGN KEY (`music_id`)
    REFERENCES `maindb`.`music` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `5`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindb`.`comments` (
  `post_id` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `id_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `2`
    FOREIGN KEY (`post_id`)
    REFERENCES `maindb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
